from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any

import yaml

P45_TARGET_MODEL_PROFILES = (
    "qrwkv_qwen_0_5b_candidate",
    "qrwkv_qwen_1_5b_candidate",
    "qrwkv_qwen_7b_stretch",
)
P45_HARDWARE_PROFILES = (
    "local_cpu_debug",
    "kaggle_tpu_v5e_8",
    "colab_tpu_v2_or_v3",
    "grant_tpu_v5e_8",
    "grant_tpu_v5e_32",
    "grant_tpu_v5e_64",
)
P45_TRAINING_MODE = "scale_hidden_only_bf16_adamw"
P45_CREATED_BY = "qrwkv_xla.scale_dry_run"
P45_DEFAULT_ARTIFACT_DIR = Path("artifacts/scale/p45_multiscale_dry_run")

EXPECTED_PARAMETER_BANDS = {
    "qrwkv_qwen_0_5b_candidate": {
        "label": "0.5B planning band",
        "minimum": 450_000_000,
        "maximum": 800_000_000,
    },
    "qrwkv_qwen_1_5b_candidate": {
        "label": "1.5B planning band",
        "minimum": 1_100_000_000,
        "maximum": 2_000_000_000,
    },
    "qrwkv_qwen_7b_stretch": {
        "label": "7B stretch planning band",
        "minimum": 5_500_000_000,
        "maximum": 8_700_000_000,
    },
}


def generate_multiscale_configs(
    output_dir: str | Path = P45_DEFAULT_ARTIFACT_DIR,
    *,
    model_profiles: tuple[str, ...] = P45_TARGET_MODEL_PROFILES,
    hardware_profiles: tuple[str, ...] = P45_HARDWARE_PROFILES,
    training_mode_name: str = P45_TRAINING_MODE,
    batch_size: int = 1,
    overwrite: bool = False,
) -> dict[str, Path]:
    from qrwkv_xla.scale_planner import (
        ScalePlanRequest,
        distill_config_yaml,
        make_plan,
        plan_to_dict,
        resolve_hardware_profile,
        resolve_model_profile,
        resolve_training_mode,
    )
    from qrwkv_xla.tracking.json_io import write_json

    out = _prepare_output_dir(output_dir, overwrite=overwrite)
    config_dir = out / "configs"
    config_dir.mkdir(parents=True, exist_ok=True)

    mode = resolve_training_mode(training_mode_name)
    plans: list[dict[str, Any]] = []
    validations: dict[str, Any] = {}
    fit_matrix: dict[str, Any] = {
        "phase": "P45",
        "status": "planning_only_and_dry_run_only",
        "created_by": P45_CREATED_BY,
        "training_mode": training_mode_name,
        "models": {},
        "memory_units": "bytes_and_gibibytes",
        "caveats": _caveats(),
    }

    for model_name in model_profiles:
        model = resolve_model_profile(model_name)
        validation = validate_model_shape_and_parameters(model)
        validations[model_name] = validation
        model_plans: dict[str, Any] = {}
        representative_plan = None
        for hardware_name in hardware_profiles:
            hardware = resolve_hardware_profile(hardware_name)
            plan = make_plan(
                ScalePlanRequest(
                    model_profile=model,
                    hardware_profile=hardware,
                    training_mode=mode,
                    sequence_length=model.sequence_length_default,
                    batch_size=batch_size,
                    microbatch_size=1,
                    grad_accum_steps=max(1, batch_size),
                )
            )
            plan_dict = plan_to_dict(plan)
            plan_dict["expected_parameter_band"] = parameter_band_status(
                model_name, plan.parameter_estimate.total_params
            )
            plan_dict["shape_parameter_validation"] = validation
            plans.append(plan_dict)
            model_plans[hardware_name] = fit_matrix_cell(plan_dict)
            if representative_plan is None:
                representative_plan = plan
        fit_matrix["models"][model_name] = model_plans
        if representative_plan is not None:
            config_text = distill_config_yaml(representative_plan)
            config_text = config_text.replace(
                "# Generated by P34 scale planner.\n",
                "# Generated by P45 multi-scale config dry-run.\n",
            )
            config_text = config_text.replace(
                "# Planning estimate only; not hardware-validated.\n",
                "# Planning estimate only; P45 dry-run config, "
                "not hardware-validated.\n",
            )
            (config_dir / f"{model_name}.yaml").write_text(
                config_text, encoding="utf-8"
            )

    report = {
        "phase": "P45",
        "status": "planning_only_and_dry_run_only",
        "created_by": P45_CREATED_BY,
        "artifact_dir": str(out),
        "model_profiles": list(model_profiles),
        "hardware_profiles": list(hardware_profiles),
        "training_mode": training_mode_name,
        "safe_init_policy": safe_init_policy(),
        "shape_parameter_validation": validations,
        "caveats": _caveats(),
        "recommended_first_real_qwen0_5b_run": first_real_qwen_0_5b_summary(),
        "plans": plans,
    }
    paths = {
        "scale_plan_report": write_json(out / "scale_plan_report.json", report),
        "fit_matrix": write_json(out / "fit_matrix.json", fit_matrix),
        "markdown_report": _write_scale_plan_markdown(
            out / "P45_SCALE_PLAN_REPORT.md", report, fit_matrix
        ),
    }
    _write_results_markdown(out / "P45_RESULTS.md", report, fit_matrix, None)
    return paths


def run_shape_dry_run(
    output_dir: str | Path = P45_DEFAULT_ARTIFACT_DIR,
    *,
    model_profiles: tuple[str, ...] = P45_TARGET_MODEL_PROFILES,
    hardware_profiles: tuple[str, ...] = P45_HARDWARE_PROFILES,
    metadata_only: bool = True,
    materialize_init: bool = False,
    allow_large_materialization: bool = False,
    checkpoint_skeleton: bool = True,
    scale_plan_path: str | Path | None = None,
    overwrite: bool = False,
) -> dict[str, Any]:
    from qrwkv_xla.scale_planner import (
        estimate_qwen_reference_parameters,
        resolve_model_profile,
    )
    from qrwkv_xla.tracking.json_io import write_json

    plan_payload = _load_scale_plan(scale_plan_path)
    out = _prepare_dry_run_output_dir(output_dir, overwrite=overwrite)
    selected_models = _profiles_from_scale_plan(plan_payload) or list(model_profiles)
    selected_hardware = _hardware_from_scale_plan(plan_payload) or list(
        hardware_profiles
    )
    fit_by_model = _fit_by_model_from_scale_plan(plan_payload)
    if not fit_by_model:
        fit_by_model = build_fit_by_model(
            tuple(selected_models),
            tuple(selected_hardware),
            P45_TRAINING_MODE,
        )

    results = []
    for model_name in selected_models:
        profile = resolve_model_profile(model_name)
        params = estimate_qwen_reference_parameters(profile)
        validation = validate_model_shape_and_parameters(profile)
        materialized = False
        materialization_status = "metadata_only_not_requested"
        if materialize_init:
            if _allows_materialization(profile, allow_large_materialization):
                _materialize_tiny_params(profile)
                materialized = True
                materialization_status = "materialized"
            else:
                materialization_status = "blocked_by_safe_init_policy"

        skeleton_status = {
            "enabled": checkpoint_skeleton,
            "status": "skipped",
            "manifest_path": None,
            "model_config_path": None,
            "metadata_path": None,
            "readback": None,
        }
        if checkpoint_skeleton:
            skeleton_status = write_checkpoint_skeleton_bundle(
                out / "checkpoint_skeletons" / model_name,
                profile,
                params.total_params,
            )

        item = {
            "phase": "P45",
            "model_profile": model_name,
            "status": "metadata_only_validated" if metadata_only else "validated",
            "metadata_only": metadata_only,
            "materialized": materialized,
            "materialization_status": materialization_status,
            "safe_init_policy": safe_init_policy(),
            "config": model_config_payload(profile),
            "parameter_estimate": {
                "total_parameters": params.total_params,
                "components": params.components,
                "assumptions": params.assumptions,
            },
            "expected_parameter_band": parameter_band_status(
                model_name, params.total_params
            ),
            "shape_parameter_validation": validation,
            "shape_metadata": parameter_shape_metadata(profile),
            "state_metadata": recurrent_state_metadata(profile),
            "fit_by_hardware": fit_by_model.get(model_name, {}),
            "checkpoint_skeleton": skeleton_status,
            "warnings": validation["warnings"],
            "caveats": _caveats(),
        }
        write_json(out / "dry_runs" / model_name / "metadata_dry_run.json", item)
        results.append(item)

    payload = {
        "phase": "P45",
        "status": "dry_run_only",
        "created_by": P45_CREATED_BY,
        "artifact_dir": str(out),
        "default_safe": True,
        "metadata_only_default": True,
        "materialize_init_requested": materialize_init,
        "allow_large_materialization": allow_large_materialization,
        "scale_plan_input": str(scale_plan_path) if scale_plan_path else None,
        "safe_init_policy": safe_init_policy(),
        "caveats": _caveats(),
        "dry_runs": results,
    }
    write_json(out / "multiscale_shape_dry_run_report.json", payload)
    _write_dry_run_markdown(out / "P45_DRY_RUN_REPORT.md", payload)
    _write_results_markdown(out / "P45_RESULTS.md", plan_payload, None, payload)
    return payload


def build_fit_by_model(
    model_profiles: tuple[str, ...],
    hardware_profiles: tuple[str, ...],
    training_mode_name: str,
) -> dict[str, dict[str, Any]]:
    from qrwkv_xla.scale_planner import (
        ScalePlanRequest,
        make_plan,
        plan_to_dict,
        resolve_hardware_profile,
        resolve_model_profile,
        resolve_training_mode,
    )

    mode = resolve_training_mode(training_mode_name)
    rows: dict[str, dict[str, Any]] = {}
    for model_name in model_profiles:
        model = resolve_model_profile(model_name)
        rows[model_name] = {}
        for hardware_name in hardware_profiles:
            hardware = resolve_hardware_profile(hardware_name)
            plan = make_plan(
                ScalePlanRequest(
                    model_profile=model,
                    hardware_profile=hardware,
                    training_mode=mode,
                    sequence_length=model.sequence_length_default,
                    batch_size=1,
                    microbatch_size=1,
                    grad_accum_steps=1,
                )
            )
            rows[model_name][hardware_name] = fit_matrix_cell(plan_to_dict(plan))
    return rows


def fit_matrix_cell(plan_dict: dict[str, Any]) -> dict[str, Any]:
    memory = plan_dict["memory_estimate"]
    components = memory["components"]
    hardware = plan_dict["hardware_profile"]
    fit = plan_dict["fit"]
    component_bytes = {
        "estimated_parameter_memory": components["weights"],
        "estimated_optimizer_memory": (
            components["gradients"] + components["optimizer_state"]
        ),
        "activation_sequence_memory_estimate": (
            components["activations_estimate"]
            + components["wkv_recurrent_state"]
            + components["shift_state"]
            + components["input_ids_and_masks"]
        ),
        "target_logits_hidden_target_memory_estimate": (
            components["teacher_hidden_targets_per_batch"]
            + components["teacher_logits_targets_per_batch"]
        ),
        "checkpoint_memory_estimate": components["checkpoint_size_estimate"],
        "xla_overhead_reserve": components["xla_overhead_reserve"],
        "total_estimate": memory["total_bytes"],
    }
    interpretation = memory_interpretation(hardware)
    classification = fit["fit"]
    notes = _fit_notes(plan_dict, interpretation)
    return {
        "memory_fit": classification,
        "fit_classification": classification,
        "metadata_only_dry_run_status": "supported",
        "dry_run_support": "metadata_only",
        "recommended_training_mode": recommended_training_mode(
            classification, plan_dict, interpretation
        ),
        "memory_interpretation": interpretation,
        "estimated_total_gb": fit["estimated_total_gb"],
        "available_memory_gb": fit["available_memory_gb"],
        "safety_margin_gb": fit["safety_margin_gb"],
        "utilization": fit["utilization"],
        "limiting_factor": fit["limiting_factor"],
        "component_estimates_bytes": component_bytes,
        "component_estimates_gib": {
            key: round(value / (1024**3), 4) for key, value in component_bytes.items()
        },
        "notes": notes,
        "warning": "; ".join(notes),
        "planner_warnings": fit["warnings"],
    }


def recommended_training_mode(
    classification: str, plan_dict: dict[str, Any], interpretation: str
) -> str:
    model_name = plan_dict["model_profile"]["name"]
    hardware = plan_dict["hardware_profile"]
    if classification == "no":
        return "not_recommended"
    if model_name.endswith("7b_stretch"):
        return (
            "hidden_only"
            if "requires_pjit_sharding" in interpretation
            else "not_recommended"
        )
    if hardware["device_count"] >= 32 and classification in {"yes", "maybe"}:
        return "hidden_plus_topk_logits"
    if classification == "yes" and hardware["device_kind"] == "gpu":
        return "hidden_plus_full_logits"
    return "hidden_only"


def memory_interpretation(hardware: dict[str, Any]) -> str:
    if hardware["device_kind"] == "tpu" and hardware["device_count"] > 1:
        if hardware.get("supports_pjit"):
            return "aggregate_slice_requires_pjit_sharding"
        return "aggregate_slice_metadata_only_no_pjit_runtime"
    return "single_device_estimate"


def parameter_shape_metadata(profile: Any) -> dict[str, Any]:
    layers = profile.num_layers
    hidden = profile.hidden_size
    kv_hidden = profile.kv_hidden_size
    mlp = profile.effective_mlp_hidden_size
    shapes: dict[str, Any] = {
        "token_embedding.weight": [profile.vocab_size, hidden],
        "layers.input_layernorm.weight": [layers, hidden],
        "layers.post_attention_layernorm.weight": [layers, hidden],
        "layers.self_attn.q_proj.weight": [layers, hidden, hidden],
        "layers.self_attn.k_proj.weight": [layers, hidden, kv_hidden],
        "layers.self_attn.v_proj.weight": [layers, hidden, kv_hidden],
        "layers.self_attn.w_proj.weight": [layers, hidden, hidden],
        "layers.self_attn.a_proj.weight": [layers, hidden, hidden],
        "layers.self_attn.b_proj.weight": [layers, hidden, hidden],
        "layers.self_attn.g_proj.weight": [layers, hidden, hidden],
        "layers.self_attn.o_proj.weight": [layers, hidden, hidden],
        "layers.self_attn.time_bias": [layers, hidden],
        "layers.self_attn.time_mix": [layers, hidden],
        "layers.mlp.gate_proj.weight": [layers, hidden, mlp],
        "layers.mlp.up_proj.weight": [layers, hidden, mlp],
        "layers.mlp.down_proj.weight": [layers, mlp, hidden],
        "final_layernorm.weight": [hidden],
    }
    if profile.emit_logits and not profile.tie_embeddings:
        shapes["lm_head.weight"] = [hidden, profile.vocab_size]
        shapes["lm_head.bias"] = [profile.vocab_size]
    elif profile.emit_logits:
        shapes["lm_head_bias"] = [profile.vocab_size]
    return {
        "backend": profile.backend,
        "dtype_default": profile.dtype_default,
        "shapes": shapes,
    }


def recurrent_state_metadata(profile: Any, *, batch_size: int = 1) -> dict[str, Any]:
    return {
        "wkv_matrix_state": [
            profile.num_layers,
            batch_size,
            profile.num_heads,
            profile.resolved_head_size,
            profile.resolved_head_size,
        ],
        "shift_state": [profile.num_layers, batch_size, profile.hidden_size],
        "next_position": [],
    }


def checkpoint_skeleton_payload(profile: Any, total_parameters: int) -> dict[str, Any]:
    return {
        "schema_version": "p45-checkpoint-skeleton-v1",
        "created_by": P45_CREATED_BY,
        "status": "metadata_only_checkpoint_skeleton",
        "planning_only": True,
        "dry_run_only": True,
        "student_architecture": profile.backend,
        "student_config": model_config_payload(profile),
        "estimated_total_parameters": total_parameters,
        "param_shapes": parameter_shape_metadata(profile)["shapes"],
        "state_shapes": recurrent_state_metadata(profile),
        "notes": _caveats(),
    }


def write_checkpoint_skeleton_bundle(
    output_dir: str | Path, profile: Any, total_parameters: int
) -> dict[str, Any]:
    from qrwkv_xla.tracking.json_io import write_json

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    metadata = checkpoint_skeleton_payload(profile, total_parameters)
    model_config = {
        "planning_only": True,
        "profile_name": profile.name,
        "student": model_config_payload(profile),
    }
    metadata_path = write_json(out / "checkpoint_metadata.json", metadata)
    model_config_path = out / "model_config.yaml"
    model_config_path.write_text(
        yaml.safe_dump(model_config, sort_keys=False), encoding="utf-8"
    )
    manifest = {
        "schema_version": "p45-checkpoint-manifest-v1",
        "created_by": P45_CREATED_BY,
        "status": "metadata_only_checkpoint_skeleton",
        "profile_name": profile.name,
        "files": {
            "model_config": "model_config.yaml",
            "checkpoint_metadata": "checkpoint_metadata.json",
        },
        "expected_total_parameters": total_parameters,
        "planning_only": True,
        "dry_run_only": True,
    }
    manifest_path = write_json(out / "checkpoint_manifest.json", manifest)
    readback = validate_checkpoint_skeleton_bundle(out)
    return {
        "enabled": True,
        "status": "validated" if readback["status"] == "valid" else "invalid",
        "validated": readback["status"] == "valid",
        "manifest_path": str(manifest_path),
        "model_config_path": str(model_config_path),
        "metadata_path": str(metadata_path),
        "readback": readback,
    }


def validate_checkpoint_skeleton(path: str | Path) -> bool:
    payload = json.loads(Path(path).read_text(encoding="utf-8"))
    return _validate_checkpoint_metadata(payload)["status"] == "valid"


def validate_checkpoint_skeleton_bundle(path: str | Path) -> dict[str, Any]:
    root = Path(path)
    errors: list[str] = []
    manifest_path = root / "checkpoint_manifest.json"
    model_config_path = root / "model_config.yaml"
    metadata_path = root / "checkpoint_metadata.json"
    for required_path in (manifest_path, model_config_path, metadata_path):
        if not required_path.is_file():
            errors.append(f"missing {required_path.name}")
    if errors:
        return {"status": "invalid", "errors": errors}

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    model_config = yaml.safe_load(model_config_path.read_text(encoding="utf-8"))
    metadata_status = _validate_checkpoint_metadata(metadata)
    if metadata_status["status"] != "valid":
        errors.extend(metadata_status["errors"])
    if manifest.get("schema_version") != "p45-checkpoint-manifest-v1":
        errors.append("invalid manifest schema_version")
    if model_config.get("planning_only") is not True:
        errors.append("model_config planning_only must be true")
    if manifest.get("profile_name") != model_config.get("profile_name"):
        errors.append("manifest/model_config profile mismatch")
    return {
        "status": "valid" if not errors else "invalid",
        "errors": errors,
        "profile_name": manifest.get("profile_name"),
        "files_read": [
            str(manifest_path),
            str(model_config_path),
            str(metadata_path),
        ],
    }


def model_config_payload(profile: Any) -> dict[str, Any]:
    return {
        "profile_name": profile.name,
        "backend": profile.backend,
        "vocab_size": profile.vocab_size,
        "hidden_size": profile.hidden_size,
        "num_layers": profile.num_layers,
        "num_heads": profile.num_heads,
        "num_kv_heads": profile.num_kv_heads,
        "head_size": profile.resolved_head_size,
        "intermediate_size": profile.effective_mlp_hidden_size,
        "sequence_length_default": profile.sequence_length_default,
        "dtype_default": profile.dtype_default,
        "emit_logits": profile.emit_logits,
        "tie_embeddings": profile.tie_embeddings,
        "status": profile.status,
    }


def validate_model_shape_and_parameters(profile: Any) -> dict[str, Any]:
    from qrwkv_xla.scale_planner import (
        estimate_qwen_reference_parameters,
        validate_model_profile,
    )

    warnings: list[str] = []
    errors: list[str] = []
    try:
        validate_model_profile(profile)
    except ValueError as exc:
        errors.append(str(exc))
    params = estimate_qwen_reference_parameters(profile)
    shapes = parameter_shape_metadata(profile)["shapes"]
    for name, shape in shapes.items():
        if any(dim <= 0 for dim in shape):
            errors.append(f"{name} contains non-positive dimensions: {shape}")
    if shapes["token_embedding.weight"] != [profile.vocab_size, profile.hidden_size]:
        errors.append("token embedding shape does not match vocab/hidden size")
    if profile.kv_hidden_size > profile.hidden_size:
        warnings.append("kv hidden size exceeds hidden size")
    if profile.name.endswith("7b_stretch"):
        warnings.append("7B stretch shape is metadata-only unless sharding is added.")
    band = parameter_band_status(profile.name, params.total_params)
    if band["status"] == "out_of_band_warning":
        warnings.append("Estimated parameter count is outside the expected band.")
    warnings.extend(validation_warnings(profile, params.total_params))
    return {
        "status": "fail" if errors else "pass_with_warnings" if warnings else "pass",
        "errors": errors,
        "warnings": list(dict.fromkeys(warnings)),
        "parameter_band_status": band,
        "checked_shape_count": len(shapes),
    }


def parameter_band_status(model_name: str, total_parameters: int) -> dict[str, Any]:
    band = EXPECTED_PARAMETER_BANDS.get(model_name)
    if band is None:
        return {
            "status": "not_applicable",
            "total_parameters": total_parameters,
        }
    ok = int(band["minimum"]) <= total_parameters <= int(band["maximum"])
    return {
        **band,
        "total_parameters": total_parameters,
        "status": "in_band" if ok else "out_of_band_warning",
    }


def validation_warnings(profile: Any, total_parameters: int) -> list[str]:
    warnings = [
        "Planning-only / dry-run-only output; no real training was run.",
        "Default metadata-only path does not materialize full parameter arrays.",
    ]
    if profile.name.endswith("7b_stretch"):
        warnings.append("7B stretch profile is not claimed to train on one device.")
    band = parameter_band_status(profile.name, total_parameters)
    if band["status"] == "out_of_band_warning":
        warnings.append("Estimated parameter count is outside the expected band.")
    return warnings


def safe_init_policy() -> dict[str, Any]:
    return {
        "default": "metadata_only",
        "materialize_init_default": False,
        "large_profile_materialization": (
            "blocked_without_explicit_allow_large_materialization"
        ),
        "allowed_without_override": ["tiny_debug", "debug-status profiles"],
    }


def first_real_qwen_0_5b_summary() -> dict[str, Any]:
    return {
        "profile": "qrwkv_qwen_0_5b_candidate",
        "recommended_hardware": "grant_tpu_v5e_8_or_larger",
        "sequence_length": 1024,
        "global_batch_size": 1,
        "microbatch_size": 1,
        "training_mode": "hidden_only",
        "targets": "pre-generated hidden targets only",
        "checkpoint_policy": (
            "start from metadata skeleton then real tiny/init smoke before scale"
        ),
        "required_before_run": [
            "real TPU backend selected",
            "teacher hidden-target bundle generated separately",
            "pjit/model sharding plan if using aggregate TPU memory",
            "no full logits unless top-k/chunked target path exists",
        ],
    }


def _allows_materialization(profile: Any, allow_large: bool) -> bool:
    return allow_large or profile.status == "debug" or profile.name.startswith("tiny")


def _materialize_tiny_params(profile: Any) -> None:
    import jax

    from qrwkv_xla.students.rwkv7_qwen_reference import (
        RWKV7QwenReferenceConfig,
        RWKV7QwenReferenceStudent,
    )

    config = RWKV7QwenReferenceConfig(
        vocab_size=profile.vocab_size,
        hidden_size=profile.hidden_size,
        num_layers=profile.num_layers,
        num_heads=profile.num_heads,
        num_kv_heads=profile.num_kv_heads,
        intermediate_size=profile.effective_mlp_hidden_size,
        emit_logits=profile.emit_logits,
        tie_embeddings=profile.tie_embeddings,
    )
    RWKV7QwenReferenceStudent(config).init_params(jax.random.PRNGKey(0))


def _prepare_output_dir(output_dir: str | Path, *, overwrite: bool) -> Path:
    out = Path(output_dir)
    if overwrite and out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True, exist_ok=True)
    return out


def _prepare_dry_run_output_dir(output_dir: str | Path, *, overwrite: bool) -> Path:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    if overwrite:
        for child in (
            out / "dry_runs",
            out / "checkpoint_skeletons",
            out / "multiscale_shape_dry_run_report.json",
            out / "P45_DRY_RUN_REPORT.md",
            out / "P45_RESULTS.md",
        ):
            if child.is_dir():
                shutil.rmtree(child)
            elif child.exists():
                child.unlink()
    return out


def _load_scale_plan(scale_plan_path: str | Path | None) -> dict[str, Any] | None:
    if scale_plan_path is None:
        return None
    return json.loads(Path(scale_plan_path).read_text(encoding="utf-8"))


def _profiles_from_scale_plan(payload: dict[str, Any] | None) -> list[str]:
    if not payload:
        return []
    return list(payload.get("model_profiles", []))


def _hardware_from_scale_plan(payload: dict[str, Any] | None) -> list[str]:
    if not payload:
        return []
    return list(payload.get("hardware_profiles", []))


def _fit_by_model_from_scale_plan(
    payload: dict[str, Any] | None,
) -> dict[str, dict[str, Any]]:
    if not payload:
        return {}
    rows: dict[str, dict[str, Any]] = {}
    for plan in payload.get("plans", []):
        model_name = plan["model_profile"]["name"]
        hardware_name = plan["hardware_profile"]["name"]
        rows.setdefault(model_name, {})[hardware_name] = fit_matrix_cell(plan)
    return rows


def _fit_notes(plan_dict: dict[str, Any], interpretation: str) -> list[str]:
    notes = [
        "metadata-only dry-run is supported",
        "planning estimate only",
        f"memory interpretation: {interpretation}",
    ]
    hardware = plan_dict["hardware_profile"]
    if hardware["device_kind"] == "tpu" and hardware["device_count"] > 1:
        notes.append("aggregate memory is not a one-device training claim")
        notes.append(
            "real training requires pjit/model sharding work not delivered by P45"
        )
    if plan_dict["model_profile"]["name"].endswith("7b_stretch"):
        notes.append(
            "7B stretch is not recommended without sharding and target pipeline work"
        )
    notes.extend(plan_dict["fit"]["warnings"])
    return list(dict.fromkeys(notes))


def _validate_checkpoint_metadata(payload: dict[str, Any]) -> dict[str, Any]:
    required = {
        "schema_version",
        "created_by",
        "status",
        "student_architecture",
        "student_config",
        "param_shapes",
        "state_shapes",
    }
    errors = []
    missing = sorted(required.difference(payload))
    if missing:
        errors.append(f"missing keys: {missing}")
    if payload.get("schema_version") != "p45-checkpoint-skeleton-v1":
        errors.append("invalid metadata schema_version")
    if payload.get("status") != "metadata_only_checkpoint_skeleton":
        errors.append("invalid metadata status")
    if not payload.get("param_shapes"):
        errors.append("param_shapes must be non-empty")
    return {"status": "valid" if not errors else "invalid", "errors": errors}


def _write_scale_plan_markdown(
    path: Path, report: dict[str, Any], fit_matrix: dict[str, Any]
) -> Path:
    lines = [
        "# P45 Scale Plan Report",
        "",
        (
            "Status: planning-only and dry-run-only. No real training, pjit, "
            "or benchmark run is implied."
        ),
        "",
        "## Model Profiles",
    ]
    for model_name, validation in report["shape_parameter_validation"].items():
        band = validation["parameter_band_status"]
        lines.append(
            "- "
            f"{model_name}: {band['total_parameters']:,} parameters, "
            f"{band['status']}, validation={validation['status']}"
        )
    lines.extend(["", "## Fit Matrix"])
    hardware = report["hardware_profiles"]
    lines.append("| model | " + " | ".join(hardware) + " |")
    lines.append("| --- | " + " | ".join("---" for _ in hardware) + " |")
    for model_name, rows in fit_matrix["models"].items():
        cells = [
            (
                f"{rows[name]['fit_classification']} / "
                f"{rows[name]['recommended_training_mode']} / "
                f"{rows[name]['component_estimates_gib']['total_estimate']:.2f} GiB"
            )
            for name in hardware
        ]
        lines.append(f"| {model_name} | " + " | ".join(cells) + " |")
    lines.extend(["", "## First Real Qwen0.5B Run Shape"])
    first = report["recommended_first_real_qwen0_5b_run"]
    lines.append(
        f"- {first['profile']}: batch={first['global_batch_size']}, "
        f"microbatch={first['microbatch_size']}, seq={first['sequence_length']}, "
        f"mode={first['training_mode']}"
    )
    lines.extend(["", "## Caveats"])
    lines.extend(f"- {item}" for item in _caveats())
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _write_dry_run_markdown(path: Path, payload: dict[str, Any]) -> Path:
    lines = [
        "# P45 Multiscale Shape Dry-Run Report",
        "",
        (
            "Status: metadata-first dry-run only. Full arrays are not "
            "materialized by default."
        ),
        "",
    ]
    for item in payload["dry_runs"]:
        skeleton = item["checkpoint_skeleton"]
        lines.append(
            "- "
            f"{item['model_profile']}: "
            f"{item['parameter_estimate']['total_parameters']:,} params, "
            f"validation={item['shape_parameter_validation']['status']}, "
            f"skeleton={skeleton['status']}, "
            f"materialization={item['materialization_status']}"
        )
    lines.extend(["", "## Caveats"])
    lines.extend(f"- {item}" for item in _caveats())
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _write_results_markdown(
    path: Path,
    scale_report: dict[str, Any] | None,
    fit_matrix: dict[str, Any] | None,
    dry_run_payload: dict[str, Any] | None,
) -> Path:
    lines = [
        "# P45 Results",
        "",
        "P45 completed the bounded multi-scale config and metadata dry-run surface.",
        "",
        "## Status",
        "- Config generation: planned, validated, and written under `configs/`.",
        "- Fit reporting: component estimates are planning-only, not measured memory.",
        (
            "- Metadata dry-runs: default safe path; full large model arrays "
            "are not allocated."
        ),
        (
            "- Checkpoint skeletons: metadata bundles are written and read "
            "back when dry-run is executed."
        ),
        "",
        "## Required Artifacts",
        "- `P45_RESULTS.md`",
        "- `P45_SCALE_PLAN_REPORT.md`",
        "- `scale_plan_report.json`",
        "- `fit_matrix.json`",
        "- `configs/*.yaml`",
        "- `dry_runs/*/metadata_dry_run.json`",
        "- `checkpoint_skeletons/*/checkpoint_manifest.json`",
        "- `checkpoint_skeletons/*/model_config.yaml`",
        "- `checkpoint_skeletons/*/checkpoint_metadata.json`",
        "",
        "## Recommended First Real Qwen0.5B Run",
    ]
    first = first_real_qwen_0_5b_summary()
    lines.append(
        f"- Profile `{first['profile']}`, sequence {first['sequence_length']}, "
        f"global batch {first['global_batch_size']}, microbatch "
        f"{first['microbatch_size']}, "
        f"mode `{first['training_mode']}` on `{first['recommended_hardware']}`."
    )
    lines.extend(
        [
            "",
            "## Materialization Policy",
            "- Default status is metadata-only.",
            "- Tiny/debug profile init may be materialized.",
            "- Large profile init is blocked unless explicitly overridden.",
        ]
    )
    if dry_run_payload:
        lines.extend(["", "## Dry-Run Readback"])
        for item in dry_run_payload["dry_runs"]:
            readback = item["checkpoint_skeleton"].get("readback") or {
                "status": "skipped"
            }
            lines.append(
                "- "
                f"{item['model_profile']}: materialization="
                f"{item['materialization_status']}, "
                f"checkpoint_readback={readback['status']}"
            )
    lines.extend(["", "## Caveats"])
    lines.extend(f"- {item}" for item in _caveats())
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _caveats() -> list[str]:
    return [
        "P45 artifacts are planning-only and dry-run-only.",
        (
            "Metadata-only dry-runs validate shapes and skeleton metadata "
            "without full tensor allocation."
        ),
        (
            "TPU fit uses aggregate memory estimates only; it is not evidence "
            "of working model sharding."
        ),
        (
            "P45 does not implement pjit, distributed execution, Pallas "
            "kernels, or WandB integration."
        ),
        (
            "No full Qwen teacher target generation, training run, benchmark, "
            "or release artifact is produced."
        ),
        (
            "7B results must not be read as one-device trainability or "
            "measured full-scale memory."
        ),
    ]
