from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]


def test_plan_model_scale_cli_writes_yaml_and_distill_config(tmp_path: Path) -> None:
    output = tmp_path / "plan.yaml"
    distill = tmp_path / "distill.yaml"
    result = subprocess.run(
        [
            sys.executable,
            str(ROOT / "scripts" / "plan_model_scale.py"),
            "--model-profile",
            "tiny_debug",
            "--hardware-profile",
            "local_cpu_16gb",
            "--training-mode",
            "smoke_hidden_sgd",
            "--sequence-length",
            "32",
            "--batch-size",
            "1",
            "--output",
            str(output),
            "--emit-distill-config",
            str(distill),
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    assert "planning-only estimate" in result.stdout
    payload = yaml.safe_load(output.read_text(encoding="utf-8"))
    assert payload["status"] == "planning_only_not_hardware_validated"
    assert payload["model_profile"]["name"] == "tiny_debug"
    assert payload["fit"]["fit"] == "yes"
    assert distill.read_text(encoding="utf-8").startswith(
        "# Generated by P34 scale planner."
    )


def test_plan_model_scale_cli_auto_json(tmp_path: Path) -> None:
    output = tmp_path / "plan.json"
    result = subprocess.run(
        [
            sys.executable,
            str(ROOT / "scripts" / "plan_model_scale.py"),
            "--model-profile",
            "qwen_7b_stretch",
            "--hardware-profile",
            "local_cpu_16gb",
            "--training-mode",
            "scale_hidden_only_bf16_adamw",
            "--target-sequence-length",
            "1024",
            "--auto",
            "--output",
            str(output),
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    payload = json.loads(output.read_text(encoding="utf-8"))
    assert payload["fit"]["fit"] == "no"
    assert payload["auto_attempts"]
    assert "auto attempts:" in result.stdout
