"""Teacher-side behavioral fingerprint capture utilities."""

from qrwkv_xla.fingerprint.aggressiveness_calibration import (
    AggressivenessCalibrationConfig,
    AggressivenessCalibrationResult,
    bootstrap_ci95,
    entry_exit_metrics,
    run_aggressiveness_calibration,
    select_profile,
)
from qrwkv_xla.fingerprint.aggressiveness_profiles import (
    PROFILE_NAMES,
    CorridorAggressivenessProfile,
    aggressiveness_profiles,
    resolve_aggressiveness_profile,
)
from qrwkv_xla.fingerprint.arc_report import (
    FingerprintArc2ReportConfig,
    FingerprintArc2ReportResult,
    build_fingerprint_arc2_report,
    run_fingerprint_arc2_report,
)
from qrwkv_xla.fingerprint.baseline_comparison import (
    FingerprintBaselineComparisonConfig,
    FingerprintBaselineComparisonResult,
    run_fingerprint_baseline_comparison,
)
from qrwkv_xla.fingerprint.capture import (
    FingerprintCaptureBudgetConfig,
    FingerprintCaptureConfig,
    FingerprintCaptureExample,
    FingerprintCaptureResult,
    FingerprintCorridorBoundsConfig,
    FingerprintExemplarReservoirCaptureConfig,
    FingerprintModeDiscoveryConfig,
    build_synthetic_capture_examples,
    capture_fingerprint_artifact,
)
from qrwkv_xla.fingerprint.corridor_measurement import (
    CorridorMeasurementConfig,
    CorridorMeasurementResult,
    corridor_distance,
    detect_corridor_entries,
    run_corridor_measurement,
)
from qrwkv_xla.fingerprint.exemplar_pass import (
    ExemplarPassConfig,
    ExemplarPassResult,
    run_exemplar_pass,
)
from qrwkv_xla.fingerprint.held_out_evaluation import (
    HeldOutFingerprintEvaluationConfig,
    HeldOutFingerprintEvaluationResult,
    paired_bootstrap_interval,
    run_held_out_fingerprint_evaluation,
    select_held_out_winner,
    stable_hash,
    validate_fingerprint_provenance,
    write_fingerprint_provenance,
)
from qrwkv_xla.fingerprint.provenance import (
    build_artifact_source_lineage,
    hash_checkpoint_bundle,
    join_sources_by_example_id,
)
from qrwkv_xla.fingerprint.quality_per_byte import (
    ControlledQualityPerByteConfig,
    ControlledQualityPerByteResult,
    FingerprintQualityPerByteExperimentConfig,
    FingerprintQualityPerByteExperimentResult,
    QualityBudgetPoint,
    evaluate_student_corridor_adherence,
    run_controlled_quality_per_byte_experiment,
    run_fingerprint_quality_per_byte_experiment,
)
from qrwkv_xla.fingerprint.real_teacher import (
    DEFAULT_TINY_REAL_TEACHER,
    TinyRealTeacherFingerprintCaptureConfig,
    TinyRealTeacherFingerprintCaptureResult,
    load_text_fixture,
    run_tiny_real_teacher_fingerprint_capture,
)
from qrwkv_xla.fingerprint.trained_baseline import (
    FingerprintTrainedBaselineConfig,
    FingerprintTrainedBaselineResult,
    masked_causal_lm_loss,
    parameter_fingerprint,
    run_fingerprint_trained_baseline_comparison,
)
from qrwkv_xla.fingerprint.training_rehearsal import (
    DEFAULT_TINY_TEXTS,
    RealTeacherFingerprintTrainingRehearsalConfig,
    RealTeacherFingerprintTrainingRehearsalResult,
    run_real_teacher_fingerprint_training_rehearsal,
)
from qrwkv_xla.fingerprint.two_cycle_experiment import (
    TwoCycleExperimentConfig,
    TwoCycleExperimentResult,
    run_two_cycle_experiment,
)

__all__ = [
    "AggressivenessCalibrationConfig",
    "AggressivenessCalibrationResult",
    "CorridorAggressivenessProfile",
    "DEFAULT_TINY_REAL_TEACHER",
    "FingerprintCaptureBudgetConfig",
    "FingerprintCaptureConfig",
    "FingerprintCaptureExample",
    "FingerprintCaptureResult",
    "FingerprintBaselineComparisonConfig",
    "FingerprintBaselineComparisonResult",
    "FingerprintArc2ReportConfig",
    "FingerprintArc2ReportResult",
    "FingerprintCorridorBoundsConfig",
    "CorridorMeasurementConfig",
    "CorridorMeasurementResult",
    "ControlledQualityPerByteConfig",
    "ControlledQualityPerByteResult",
    "ExemplarPassConfig",
    "ExemplarPassResult",
    "FingerprintExemplarReservoirCaptureConfig",
    "FingerprintModeDiscoveryConfig",
    "FingerprintQualityPerByteExperimentConfig",
    "FingerprintQualityPerByteExperimentResult",
    "FingerprintTrainedBaselineConfig",
    "FingerprintTrainedBaselineResult",
    "HeldOutFingerprintEvaluationConfig",
    "HeldOutFingerprintEvaluationResult",
    "DEFAULT_TINY_TEXTS",
    "PROFILE_NAMES",
    "QualityBudgetPoint",
    "RealTeacherFingerprintTrainingRehearsalConfig",
    "RealTeacherFingerprintTrainingRehearsalResult",
    "TinyRealTeacherFingerprintCaptureConfig",
    "TinyRealTeacherFingerprintCaptureResult",
    "TwoCycleExperimentConfig",
    "TwoCycleExperimentResult",
    "build_synthetic_capture_examples",
    "aggressiveness_profiles",
    "bootstrap_ci95",
    "build_fingerprint_arc2_report",
    "build_artifact_source_lineage",
    "capture_fingerprint_artifact",
    "corridor_distance",
    "detect_corridor_entries",
    "entry_exit_metrics",
    "evaluate_student_corridor_adherence",
    "load_text_fixture",
    "hash_checkpoint_bundle",
    "join_sources_by_example_id",
    "masked_causal_lm_loss",
    "parameter_fingerprint",
    "paired_bootstrap_interval",
    "run_fingerprint_baseline_comparison",
    "resolve_aggressiveness_profile",
    "run_aggressiveness_calibration",
    "run_fingerprint_arc2_report",
    "run_fingerprint_quality_per_byte_experiment",
    "run_fingerprint_trained_baseline_comparison",
    "run_corridor_measurement",
    "run_controlled_quality_per_byte_experiment",
    "run_exemplar_pass",
    "run_held_out_fingerprint_evaluation",
    "run_real_teacher_fingerprint_training_rehearsal",
    "run_tiny_real_teacher_fingerprint_capture",
    "run_two_cycle_experiment",
    "select_held_out_winner",
    "select_profile",
    "stable_hash",
    "validate_fingerprint_provenance",
    "write_fingerprint_provenance",
]
